import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

// Import Swiper React components
import { Swiper, SwiperSlide } from 'swiper/react';

// Import Swiper styles
import 'swiper/css';

// import required modules
import { Autoplay, Pagination, Navigation } from "swiper";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Vids Coin</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" />
        <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" rel="stylesheet" />
        
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link href="https://fonts.googleapis.com/css2?family=Inter&display=swap" rel="stylesheet" />
      </Head>

      <main>
        <Swiper
          autoplay={{
            delay: 10000,
            disableOnInteraction: false,
          }}
          loop={true}
          slidesPerView={1}
          //onSlideChange={() => console.log('slide change')}
          //onSwiper={(swiper) => console.log(swiper)}
          modules={[Autoplay]}
        >
          <SwiperSlide>
            <div className="SwiperSlide">
              <div className="container-fluid px-0">
                <div className="d-flex justify-content-between align-items-center -border-bottom header-bottom px-2 pb-2">
                  <div>
                    <img src="/logo_1.png" className="d-block logo" />
                  </div>
                  <div role="button">
                    <img src="/wallet-icon.png" className="d-block logo float-end" />
                    <small className="d-block text-white">connect</small>
                  </div>
                </div>
              </div>

              <div className="container">
                <section className="my-4">
                  <div className="d-flex justify-content-between align-items-center">
                    <div>
                      <div className="d-flex">
                        <img src="/avatar.jpg" className="rounded-pill avatar me-2" />
                        <div>
                          <small className="text-white">Owned by</small>
                          <div className="primary-text fw-bold">2304RC</div>
                        </div>
                      </div>
                    </div>
                    <div>|</div>
                    <div>
                      <div className="d-flex">
                        <div className="me-2 text-end">
                          <small className="text-white">Created by</small>
                          <div className="primary-text fw-bold">2304RC</div>
                        </div>
                        <img src="/avatar.jpg" className="rounded-pill avatar" />
                      </div>
                    </div>
                  </div>
                </section>

                <section className="position-relative">
                  <img src="https://c.tenor.com/T1ehudBJ0EYAAAAd/nfts-nft.gif" className="w-100 rounded-wpits" />
                  <div className="position-absolute live-status">Live Now</div>
                </section>

                <section>
                  <div className="d-flex justify-content-between align-items-center fs-4 mt-2">
                    <div>
                      <span className="me-3 fw-bold text-white">Equilibrium #3429</span>
                      <span className="primary-text"><i className="fas fa-qrcode"></i></span>
                    </div>
                    <div className="primary-text">
                      <i className="fas fa-heart"></i>
                    </div>
                  </div>

                  <div className="secondary-text fs-5 mt-2 card-sub-title">Our Equilibrium collection promotes balance and calm.</div>

                  <div className="d-flex justify-content-between align-items-center fs-5 mt-3 ethereum-section">
                    <div>
                      <div>
                        <span className="me-2"><i className="fab fa-ethereum fa-lg bright-text"></i></span>
                        <span className="me-2 text-white">$2000</span>
                        <span className="me-2"><i className="fas fa-info-circle primary-text" role="button" title="Creator free"></i></span>
                      </div>
                    </div>
                    <div className="primary-text">x10=</div>
                    <div>
                      <div className="text-end">
                        <span className="me-2 text-white">$2000</span>
                        <span><i className="fas fa-info-circle primary-text" role="button" title="10x multiple bid"></i></span>
                      </div>
                    </div>
                  </div>

                  <div className="d-flex justify-content-between align-items-center fs-5 mt-2 ethereum-section">
                    <div>
                      <div className="primary-text">
                        <a href="http://www.toptissue.com/vidscoin/detail-page.html" className="primary-text me-2">Detailed Revenue</a>
                        <i className="fas fa-info-circle" role="button" title="Creator free"></i>
                      </div>
                    </div>
                    <div>
                      <div className="text-end">
                        <span className="me-2 text-white">Estimated value is $20000</span>
                        <span><i className="fas fa-info-circle primary-text" role="button" title="10x multiple bid"></i></span>
                      </div>
                    </div>
                  </div>
                </section>

                <hr className="divider" />

                <section className="bid-section">
                  <div className="text-center secondary-text">Minimum Bid</div>
                  <div className="d-flex justify-content-center mt-2">
                    <div className="d-flex align-items-center fs-5 bid-operators-section">
                      <div className="me-2 btn-operators">-</div>
                      <div className="me-2 text-white">$2000</div>
                      <div className="me-2 btn-operators">+</div>
                      <div className="me-2"><i className="fas fa-info-circle primary-text" role="button" title="Bidding price"></i></div>
                      <div className="me-2"><button className="rounded-pill btn-primary-wpits">Offer</button></div>
                      <div className="me-2"><i className="fas fa-info-circle primary-text" role="button" title="Bidding price"></i></div>
                    </div>
                  </div>
                  <div className="text-center secondary-text mt-2 pb-5 mb-5">Will Be Live In <span className="primary-text">7 Days</span></div>
                </section>
              </div>
            </div>
          </SwiperSlide>
        </Swiper>

        <div className="fixed-bottom sticky-footer">
          <div className="d-flex justify-content-between align-items-center p-2">
            <div className="text-center">
              <div><i className="fas fa-home"></i></div>
              <div>Home</div>
            </div>
            <div className="text-center">
              <div><i className="fas fa-cart-arrow-down"></i></div>
              <div>Explore</div>
            </div>
            <div><i className="fas fa-plus-circle primary-text btn-add"></i></div>
            <div className="text-center">
              <div><i className="fas fa-comment-alt"></i></div>
              <div>Inbox</div>
            </div>
            <div className="text-center">
              <div><i className="fas fa-user"></i></div>
              <div>Profile</div>
            </div>
          </div>
        </div>
      </main>

      <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js"></script>
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
    </div>
  )
}
