import Head from 'next/head'
import Image from 'next/image'

export default function Login() {
  const onClickHandler = async e => {
    // console.log('clicked');
    const btnFile = document.getElementById('file');
    btnFile.click();
  }

  const onChangeHandler = async e => {
    
  }

  return (
    <div>
      <Head>
        <title>Vids Coin - Image Upload</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="../favicon.ico" />
        <link
          href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
          rel="stylesheet"
        />
        <link
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css"
          rel="stylesheet"
        />
      </Head>

      <main>
        <div className="container py-5">
          <div className="row justify-content-center">
            <div className="col-xl-5 col-lg-6 col-md-7">
              <div className="text-center">
                <div className="form-group -d-none">
                  <input className="form-control" type="file" name="file" id="file" onChange={onChangeHandler} />
                </div>
                <button className="btn btn-primary" type="submit" onClick={onClickHandler}>
                  Upload Image
                </button>
              </div>
            </div>
          </div>
        </div>
      </main>
    </div>
  )
}
